//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nbacont
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchUpLog
    {
        public int idMatchUpLog { get; set; }
        public int Quarter { get; set; }
        public string OccurTime { get; set; }
        public string Remar { get; set; }
        public int MatchUp_idMatchUp { get; set; }
        public int Team_idTeam { get; set; }
        public int Player_idPlayer { get; set; }
        public int ActionType_idActionType { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual MatchUp MatchUp { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
