//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nbacont
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchUpDetail
    {
        public int idMatchUpDetail { get; set; }
        public int Quarter { get; set; }
        public int MatchUp_idMatchUp { get; set; }
    
        public virtual MatchUp MatchUp { get; set; }
    }
}
