//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nbacont
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int idPicture { get; set; }
        public string Img { get; set; }
        public string Descriotion { get; set; }
        public int NumberOfLike { get; set; }
        public string CreateTime { get; set; }
    }
}
