//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nbacont
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.MatchUpLog = new HashSet<MatchUpLog>();
            this.PlayerTeam = new HashSet<PlayerTeam>();
        }
    
        public int idPlayer { get; set; }
        public string Name { get; set; }
        public string JoinYear { get; set; }
        public float Height { get; set; }
        public float Weight { get; set; }
        public string DateOfBirth { get; set; }
        public string College { get; set; }
        public string img { get; set; }
        public string IsRet { get; set; }
        public string RetrimentTime { get; set; }
        public string CountryCode { get; set; }
        public int Position_idPosition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchUpLog> MatchUpLog { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerTeam> PlayerTeam { get; set; }
    }
}
